### ISSUE TITLE
connect to bundles

### ISSUE THREAD

**Issue by ddtch** [modelcontextprotocol/inspector#111]
**Is your feature request related to a problem? Please describe.**
When compiling a bundle with Deno and running it in MCP, the debugger inspector functionality is not accessible. 

**Describe the solution you'd like**
Add support for connecting to the V8 inspector protocol when running Deno bundles in MCP. 

**Describe alternatives you've considered**
- Using console.log statements for debugging (cumbersome and limited visibility into program state)
- Running the code outside MCP for debugging (doesn't accurately represent the MCP runtime environment)

**Additional context**

I compile my mcp with command like 
```
deno compile --target aarch64-apple-darwin --allow-net --allow-env --allow-run --allow-sys --allow-read --allow-write --output xMcp-1.0 main.ts
```
and claude can interact with it all good, but inspector can not.

```
NotCapable: Requires env access to "NODE_EXTRA_CA_CERTS", 
specify the required permissions during compilation using 
'deno compile --allow-env' 
at Object.getEnv [as get] (ext:runtime/30_os.js:124:10) 
at HttpsClientRequest._getClient (node:https:94:35) 
at HttpsClientRequest._writeHeader (node:http:296:25) 
at HttpsClientRequest._send (node:_http_outgoing:381:12) 
at HttpsClientRequest.end (node:http:434:12) 
at writeToStream (file:///private/tmp/deno-compile-xMcp/node_modules/localhost/node-fetch/2.7.0/lib/index.js:649:8) 
at file:///private/tmp/deno-compile-xMcp/node_modules/localhost/node-fetch/2.7.0/lib/index.js:1726:3 at new Promise (<anonymous>) 
at fetch (file:///private/tmp/deno-compile-xMcp/node_modules/localhost/node-fetch/2.7.0/lib/index.js:1447:9) 
at fetchWithRetries (file:///private/tmp/deno-compile-xMcp/node_modules/localhost/twitter-api-sdk/1.2.1/dist/request.js:21:48) { name: "NotCapable" }
```

**Comment by cliffhall** [comment]
Hi @ddtch!

Could you add more specifics regarding what you're after here? I see an error message that looks like you can't compile your server. I'm having a hard time understanding the workflow you're shooting for and what changes to the inspector you're hoping will enable it. 

* You say 'debugger inspector functionality' making me think you want to debug the Inspector source while it is connected to your server.

* But you also say Claude can talk to the server but the inspector can't, which makes the previous thing not make sense because you can't debug Claude. 

Maybe walk us through the steps you want to see happen end-to-end so we can understand where the actual problem is.

**Comment by cliffhall** [comment]
Closing this one for lack of details. Feel free to reopen if you can provide some more info.
