### ISSUE TITLE
Inspector UI Crash when CallToolResult content is not an array

### ISSUE THREAD

**Issue by jacksteamdev** [modelcontextprotocol/inspector#80]
I've followed the weather example from the [docs](https://modelcontextprotocol.io/docs/first-server/typescript), and the inspector crashes when the `get_forecast` handler returns with this error in the browser:

```sh
Uncaught TypeError: f.content.map is not a function
    at u (index-jOz_Q5JL.js:185:28299)
    at qE (index-jOz_Q5JL.js:185:30526)
    at $u (index-jOz_Q5JL.js:38:16998)
    at bc (index-jOz_Q5JL.js:40:3139)
    at Th (index-jOz_Q5JL.js:40:44737)
    at Eh (index-jOz_Q5JL.js:40:39727)
    at Lx (index-jOz_Q5JL.js:40:39655)
    at ra (index-jOz_Q5JL.js:40:39508)
    at Dc (index-jOz_Q5JL.js:40:35875)
    at _h (index-jOz_Q5JL.js:40:34826)
```

[Perhaps the fastest way to explain is a quick Loom.](https://www.loom.com/share/d3d3226fcd364d73a132aa266d04409b?sid=b7fd00b5-772a-4ca8-9fc4-6c2d84db9188)

Minimal repro: https://github.com/jacksteamdev/weather-server/tree/main

**Comment by jacksteamdev** [comment]
A little bit more digging shows that the docs have the wrong return value for the handler; it should be an array.

```typescript
console.error(`Forecast for ${city}:`, forecasts);
await setTimeout(5000);
return {
  content: {
    mimeType: "application/json",
    text: JSON.stringify(forecasts, null, 2)
  } // content should be an array
};
```

The related code for this repo:
https://github.com/modelcontextprotocol/inspector/blob/2b79b6ffd46f9a468378c709386ae81b0c7e5e2f/client/src/components/ToolsTab.tsx#L42-L51

In the wild, `structuredResult.content` could be anything.
